namespace InkStainedWretch.OnePageAuthorAPI.Entities
{
    /// <summary>
    /// Represents an article and its associated metadata for the One Page Author API.
    /// </summary>
    public class Article
    {
        /// <summary>
        /// The primary key for the Article entity.
        /// </summary>
        public string id { get; set; }

        /// <summary>
        /// The unique identifier for the author, must match the format generated by Author.UniqueIdentifier().
        /// </summary>
        public string AuthorID { get; set; }

        /// <summary>
        /// The title of the article.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// The publication date of the article.
        /// </summary>
        public DateTime Date { get; set; }

        /// <summary>
        /// The name of the publication where the article appeared.
        /// </summary>
        public string Publication { get; set; }

        /// <summary>
        /// The URL to the article's page or resource.
        /// </summary>
        public Uri URL { get; set; }

        /// <summary>
        /// Default constructor. Initializes all properties to default values.
        /// </summary>
        public Article()
        {
            id = string.Empty;
            AuthorID = string.Empty;
            Title = string.Empty;
            Date = DateTime.MinValue;
            Publication = string.Empty;
            URL = new Uri("https://example.com");
        }

        /// <summary>
        /// Constructor that initializes all properties.
        /// </summary>
        public Article(Guid articleID, string authorID, string title, DateTime date, string publication, Uri url)
        {
            id = articleID.ToString();
            AuthorID = authorID;
            Title = title;
            Date = date;
            Publication = publication;
            URL = url;
        }

        /// <summary>
        /// Constructor that initializes all properties and validates AuthorID format.
        /// </summary>
        /// <param name="authorID">The unique identifier for the author.</param>
        /// <param name="title">The title of the article.</param>
        /// <param name="date">The publication date of the article.</param>
        /// <param name="publication">The name of the publication.</param>
        /// <param name="url">The URL to the article's page or resource.</param>
        /// <exception cref="ArgumentException">Thrown if authorID does not match the required format.</exception>
        public Article(Guid authorID, string title, DateTime date, string publication, Uri url)
        {
            id = Guid.NewGuid().ToString();
            AuthorID = authorID.ToString();
            Title = title;
            Date = date;
            Publication = publication;
            URL = url;
        }
    }
}
