namespace InkStainedWretch.OnePageAuthorAPI.Entities
{
    /// <summary>
    /// Represents a social profile or link associated with an author for the One Page Author API.
    /// </summary>
    public class Social
    {

        /// <summary>
        /// The primary key for the Social entity.
        /// </summary>
        public string id { get; set; }

        /// <summary>
        /// The unique identifier for the author, must match the format generated by Author.UniqueIdentifier().
        /// </summary>
        public string AuthorID { get; set; }

        /// <summary>
        /// The name of the social platform (e.g., "Twitter", "LinkedIn").
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The URL to the social profile or page.
        /// </summary>
        public Uri URL { get; set; }

        /// <summary>
        /// Default constructor. Initializes all properties to default values.
        /// </summary>
        public Social()
        {
            id = string.Empty;
            AuthorID = string.Empty;
            Name = string.Empty;
            URL = new Uri("https://example.com");
        }

        /// <summary>
        /// Constructor that initializes all properties and validates AuthorID format.
        /// </summary>
        /// <param name="authorID">The unique identifier for the author.</param>
        /// <param name="name">The name of the social platform.</param>
        /// <param name="url">The URL to the social profile or page.</param>
        /// <exception cref="ArgumentException">Thrown if authorID does not match the required format.</exception>
        public Social(Guid authorID, string name, Uri url)
        {
            id = Guid.NewGuid().ToString();
            AuthorID = authorID.ToString();
            Name = name;
            URL = url;
        }
    }
}
