# GitHub Actions workflow to build and deploy Azure Function App
name: Deploy Function App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build Function App
        run: |
          cd function-app
          dotnet build --configuration Release

      - name: Publish Function App
        run: |
          cd function-app
          dotnet publish --configuration Release --output ./publish

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: function-app/publish
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

# Required secrets:
# - AZURE_FUNCTIONAPP_NAME: Name of your Azure Function App
# - AZURE_FUNCTIONAPP_PUBLISH_PROFILE: Contents of the publish profile from Azure portal
